branch-defaults:
  default:
    environment: lcog-team-env
    group_suffix: null
  production:
    environment: lcog-team-env
environment-defaults:
  lcog-internal-env:
    branch: null
    repository: null
global:
  application_name: lcog-team
  branch: null
  default_ec2_keyname: lcog-team
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: lcog
  repository: null
  sc: git
  workspace_type: Application
