branch-defaults:
  production:
    environment: lcog-team-env
  staging:
    environment: lcog-team-staging-2-env
  staging-with-prs:
    environment: lcog-team-staging-1
environment-defaults:
  lcog-team-env:
    branch: production
    repository: null
  lcog-team-staging:
    branch: staging
    repository: null
  lcog-team-staging-1:
    branch: staging
    repository: null
  lcog-team-staging-2-env:
    branch: staging
    repository: null
global:
  application_name: lcog-team-staging-2
  branch: null
  default_ec2_keyname: lcog-team-20230802
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
