# Generated by Django 5.2.5 on 2025-10-03 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0032_employeetransition_current_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetransition',
            name='union_affiliation',
            field=models.CharField(blank=True, choices=[('Non-Represented', 'Non-Represented'), ('EA', 'EA'), ('SEIU', 'SEIU'), ('Senior Meals', 'Senior Meals'), ('Management', 'Management')], max_length=20),
        ),
    ]
