# Generated by Django 5.2.5 on 2025-10-07 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0032_employeetransition_current_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetransition',
            name='extension_remain_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeetransition',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='employeetransition',
            name='oregon_access',
            field=models.CharField(choices=[('Not needed', 'Not needed'), ('Desktop & Remote', 'Desktop & Remote'), ('Remote', 'Remote')], default='Not needed', max_length=16),
        ),
        migrations.AlterField(
            model_name='employeetransition',
            name='phone_request',
            field=models.CharField(blank=True, choices=[('New number needed', 'New number needed'), ('Remove phone', 'Remove phone'), ('Delete number', 'Delete number'), ('Reassign to:', 'Reassign to:'), ('Change name display to:', 'Change name display to:'), ('Delete voicemail box', 'Delete voicemail box'), ('No phone needed', 'No phone needed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='employeetransition',
            name='union_affiliation',
            field=models.CharField(blank=True, choices=[('Non-Represented', 'Non-Represented'), ('EA', 'EA'), ('SEIU', 'SEIU'), ('Senior Meals', 'Senior Meals'), ('Management', 'Management')], max_length=20),
        ),
    ]
