# Generated by Django 5.2.5 on 2025-10-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0033_alter_employeetransition_union_affiliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetransition',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
