# Generated by Django 5.2.5 on 2025-10-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0034_employeetransition_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetransition',
            name='extension_remain_active',
            field=models.BooleanField(default=False),
        ),
    ]
