# Generated by Django 5.2.5 on 2025-10-03 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0035_employeetransition_extension_remain_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetransition',
            name='phone_request',
            field=models.CharField(blank=True, choices=[('New number needed', 'New number needed'), ('Remove phone', 'Remove phone'), ('Delete number', 'Delete number'), ('Reassign to:', 'Reassign to:'), ('Change name display to:', 'Change name display to:'), ('Delete voicemail box', 'Delete voicemail box'), ('No phone needed', 'No phone needed')], max_length=30),
        ),
    ]
