# Generated by Django 5.2.5 on 2025-10-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0036_alter_employeetransition_phone_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetransition',
            name='oregon_access',
            field=models.CharField(choices=[('Not needed', 'Not needed'), ('Desktop & Remote', 'Desktop & Remote'), ('Remote', 'Remote')], default='Not needed', max_length=16),
        ),
    ]
