# Generated by Django 5.2.9 on 2025-12-22 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0060_alter_performancereview_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhishReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.JSONField()),
                ('organic', models.BooleanField(default=True)),
                ('processed', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.employee')),
            ],
        ),
    ]
