# Generated by Django 5.2.9 on 2026-02-13 19:22

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_securitymessage_organization'),
        ('people', '0063_reviewnote_anon_name_reviewnote_anon_org_and_more'),
        ('phish', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phishreport',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='phishreport',
            name='organic',
        ),
        migrations.CreateModel(
            name='SyntheticPhishTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('version', models.IntegerField(default=1)),
                ('subject', models.CharField(max_length=255)),
                ('body', ckeditor.fields.RichTextField()),
                ('difficulty', models.IntegerField(default=1, help_text='1 is easiest, 3 is hardest')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.organization')),
            ],
            options={
                'unique_together': {('organization', 'name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='SyntheticPhish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('clicked', models.BooleanField(default=False)),
                ('reported', models.BooleanField(default=False)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.employee')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='phish.syntheticphishtemplate')),
            ],
            options={
                'verbose_name_plural': 'Synthetic phishes',
            },
        ),
        migrations.CreateModel(
            name='TrainingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('version', models.IntegerField(default=1)),
                ('content', ckeditor.fields.RichTextField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.organization')),
            ],
            options={
                'unique_together': {('organization', 'name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='TrainingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.employee')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='phish.trainingtemplate')),
            ],
        ),
    ]
