# Generated by Django 5.2.9 on 2025-12-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phishreport',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
