# Generated by Django 5.2.9 on 2026-03-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phish', '0002_rename_timestamp_phishreport_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phishreport',
            name='status',
            field=models.CharField(choices=[('reported', 'Reported'), ('phish', 'Phish'), ('not_phish', 'Not Phish')], default='reported', max_length=255),
        ),
    ]
