# Generated by Django 5.2.9 on 2026-03-18 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_securitymessage_organization'),
        ('people', '0064_signature_is_hr'),
        ('phish', '0003_phishreport_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhishTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.organization')),
            ],
        ),
        migrations.CreateModel(
            name='PhishReportTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.employee')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phish.phishreport')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phish.phishtask')),
            ],
        ),
    ]
