# Generated by Django 6.0.3 on 2026-03-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phish', '0004_phishtask_phishreporttask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phishreport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Phish Report', 'verbose_name_plural': 'Phish Reports'},
        ),
        migrations.AddField(
            model_name='phishreport',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
