# Generated by Django 6.0.4 on 2026-04-27 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_securitymessage_organization'),
        ('phish', '0005_alter_phishreport_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhishConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phish_report_notification_email', models.EmailField(blank=True, help_text='Email address that receives a notification when a genuine phishing report is submitted.', max_length=254, null=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phish_configuration', to='mainsite.organization')),
            ],
            options={
                'verbose_name': 'Phish Configuration',
                'verbose_name_plural': 'Phish Configurations',
            },
        ),
    ]
