# Generated by Django 4.2.11 on 2025-08-21 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitymessage',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainsite.organization'),
            preserve_default=False,
        ),
    ]
