# Generated by Django 5.2.5 on 2025-12-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0058_alter_performancereview_probationary_evaluation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaturereminder',
            name='signed',
            field=models.BooleanField(default=False, verbose_name='has signed'),
        ),
    ]
