# Generated by Django 5.2.9 on 2025-12-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0059_signaturereminder_signed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancereview',
            name='status',
            field=models.CharField(choices=[('N', 'Needs evaluation'), ('EW', 'Evaluation written'), ('EA', 'Evaluation approved up to division director'), ('EP', 'Evaluation processed by HR'), ('ED', 'Evaluation approved by executive director')], default='N', max_length=2, verbose_name='review status'),
        ),
    ]
