# Generated by Django 5.2.9 on 2026-01-20 23:38

from django.db import migrations


def migrate_ed_approved_to_hr_processed(apps, schema_editor):
    """
    Change all PerformanceReview objects with status EVALUATION_ED_APPROVED
    to EVALUATION_HR_PROCESSED.
    """
    PerformanceReview = apps.get_model('people', 'PerformanceReview')
    PerformanceReview.objects.filter(status='ED').update(status='EP')


def reverse_migration(apps, schema_editor):
    """
    Reverse the migration by changing EVALUATION_HR_PROCESSED back to
    EVALUATION_ED_APPROVED (only for records that would have been changed).
    """
    # Note: This reverse migration is a best-effort approach
    # It cannot distinguish between records that were already 'EP' before
    # and those that were migrated from 'ED' to 'EP'
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0060_alter_performancereview_status'),
    ]

    operations = [
        migrations.RunPython(
            migrate_ed_approved_to_hr_processed,
            reverse_migration
        ),
    ]
