# Generated by Django 5.2.9 on 2026-01-20 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0061_auto_remove_pr_ed_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancereview',
            name='status',
            field=models.CharField(choices=[('N', 'Needs evaluation'), ('EW', 'Evaluation written'), ('EA', 'Evaluation approved by all managers'), ('EP', 'Evaluation processed by HR')], default='N', max_length=2, verbose_name='review status'),
        ),
    ]
