# Generated by Django 5.2.9 on 2026-02-10 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0062_alter_performancereview_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewnote',
            name='anon_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='unauthenticated name'),
        ),
        migrations.AddField(
            model_name='reviewnote',
            name='anon_org',
            field=models.CharField(blank=True, max_length=255, verbose_name='unauthenticated org'),
        ),
        migrations.AlterField(
            model_name='reviewnote',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes_written', to='people.employee', verbose_name='author'),
        ),
    ]
