# Generated by Django 5.2.9 on 2026-03-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0063_reviewnote_anon_name_reviewnote_anon_org_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='is_hr',
            field=models.BooleanField(default=False, verbose_name='is HR manager signature'),
        ),
    ]
