# Generated by Django 6.0.3 on 2026-04-07 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_securitymessage_organization'),
        ('people', '0064_signature_is_hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='prform',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainsite.organization'),
        ),
    ]
